_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 105
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.10.9
            "5": 0.19.4
            "6": 4.48.1
            "8":
                - 1
                - 2
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
