wandb_version: 1

base_trainable:
  value: true
batch_size:
  value: 32
dense_units:
  value: 128
dropout_rate:
  value: 0.2
epochs:
  value: 5
learning_rate:
  value: 0.01
num_dense_layers:
  value: 3
use_batchnorm:
  value: false
