_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 105
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.10.9
            "5": 0.19.4
            "6": 4.48.1
            "8":
                - 1
                - 2
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
base_trainable:
    value: false
batch_size:
    value: 32
dense_units:
    value: 128
dropout_rate:
    value: 0.5
epochs:
    value: 10
learning_rate:
    value: 1e-05
num_dense_layers:
    value: 1
use_batchnorm:
    value: false
