wandb_version: 1

base_trainable:
  value: false
batch_size:
  value: 16
dense_units:
  value: 64
dropout_rate:
  value: 0.5
epochs:
  value: 5
learning_rate:
  value: 0.001
num_dense_layers:
  value: 3
use_batchnorm:
  value: true
