wandb_version: 1

base_trainable:
  value: true
batch_size:
  value: 16
dense_units:
  value: 256
dropout_rate:
  value: 0.3
epochs:
  value: 5
learning_rate:
  value: 1.0e-05
num_dense_layers:
  value: 2
use_batchnorm:
  value: true
