wandb_version: 1

base_trainable:
  value: false
batch_size:
  value: 32
dense_units:
  value: 128
dropout_rate:
  value: 0.5
epochs:
  value: 10
learning_rate:
  value: 1.0e-05
num_dense_layers:
  value: 1
use_batchnorm:
  value: false
