_wandb:
    value:
        cli_version: 0.19.4
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 105
            "3":
                - 2
                - 7
                - 14
                - 23
                - 38
                - 39
                - 55
            "4": 3.10.9
            "5": 0.19.4
            "6": 4.48.1
            "8":
                - 1
                - 2
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
base_trainable:
    value: true
batch_size:
    value: 32
dense_units:
    value: 128
dropout_rate:
    value: 0.3
epochs:
    value: 10
learning_rate:
    value: 0.0001
num_dense_layers:
    value: 3
use_batchnorm:
    value: false
