_wandb:
    value:
        cli_version: 0.19.4
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/val_loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/accuracy
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/val_accuracy
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 105
            "3":
                - 2
                - 7
                - 13
                - 23
                - 38
                - 39
                - 55
            "4": 3.10.9
            "5": 0.19.4
            "6": 4.48.1
            "8":
                - 1
                - 2
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
